### ISSUE TITLE
re: playstore comments

### ISSUE THREAD

**Issue by 7macaw** [tananaev/rootless-logcat#1]
To expand on the play store comments:

- the way I use this is to look at logs where it's not easy to attach a proper logcat viewer. For example something gps-related, or wifi/cell network crossing. It is much easier to match what happens in the physical world (e.g. I've stepped outside the wifi range) with what happens in the app if I could look at the logs for the app right when I'm moving around. Certainly I can copy the log and email it to myself, but then I'd have to remember the exact time when something happened to match it with the log later. So filtering by bundle id would be immensely helpful.

- timestamps aren't even shown on the play store screenshots, so I'm sure it's easy to reproduce ;)

**Comment by tananaev** [comment]
1. I'll try to implement it as soon as I have some free time

2. lol.. I didn't even noticed it. I guess default logcat format is different for different devices/version. When I implemented it, I definitely had timestamps. Then I took screenshots on another device for Google Play, but I didn't notice that time wasn't there. I'll fix it as well.

Thanks for feedback.

**Comment by tananaev** [comment]
I have fixed both problems. New version should be available on Google Play in a couple of hours.
