### ISSUE TITLE
Publish APK at Github?

### ISSUE THREAD

**Issue by IzzySoft** [tananaev/rootless-logcat#3]
Would you consider publishing the `.apk` here at Github, for folks without Playstore? Preferably in the `releases/` section (see: [Creating Releases](https://help.github.com/articles/creating-releases/) in the GitHub Help), which is really easy. If you'd do so, I could automatically pick it up (within 24h or your attaching it there) and offer it via [my F-Droid compatible repo](https://android.izzysoft.de/repo), and those folks would get automated updates even.

**Comment by tananaev** [comment]
I have published latest version in releases.

**Comment by IzzySoft** [comment]
Wow – that was fast! Excellent! As promised, find it [here](https://apt.izzysoft.de/fdroid/index/apk/com.tananaev.logcat). Oh, and also find it [here](https://android.izzysoft.de/applists/category/named/tools_logcat#group_931) :innocent:

Thanks a lot!

**Comment by IzzySoft** [comment]
@tananaev as the app has made it successfully to the "official repo" (see #4 – and congratulations!), I will now "unlist" it from mine. Should need arise, be welcome to contact me anytime and have it re-listed. Thanks for your support!
