### ISSUE TITLE
Publishing on F-Droid?

### ISSUE THREAD

**Issue by relan** [tananaev/rootless-logcat#4]
I'd love to see your app on [F-Droid](https://f-droid.org). If you are OK with this, I'll add it.

**Comment by tananaev** [comment]
Sure, I'm OK with that.

**Comment by relan** [comment]
Could you please add `LICENSE` or `COPYING` file to the repository? Though README clearly states the license, it's better to be on the safe side.

**Comment by relan** [comment]
Here it is: https://f-droid.org/app/com.tananaev.logcat

You can add [F-Droid badge](https://gitlab.com/fdroid/artwork/blob/master/badge/README.md) if you wish.

**Comment by tananaev** [comment]
Thanks. I've added a badge:

https://github.com/tananaev/rootless-logcat
